
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A455L
 */
public class Frame1 extends javax.swing.JFrame {

     String temp ="";
     Double ti, bt, h1;
    
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        pa = new javax.swing.JRadioButton();
        pi = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bbideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jTextField3.setText("jTextField3");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 40, 20);

        jLabel3.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 90, 14);

        jLabel5.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 110, 20);

        nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(150, 70, 260, 30);

        tinggi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tinggi.setBorder(null);
        getContentPane().add(tinggi);
        tinggi.setBounds(150, 110, 60, 30);

        bb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bb.setBorder(null);
        getContentPane().add(bb);
        bb.setBounds(150, 150, 60, 30);

        pa.setBackground(new java.awt.Color(255, 204, 51));
        buttonGroup1.add(pa);
        pa.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        pa.setForeground(new java.awt.Color(255, 255, 255));
        pa.setText("Laki - laki");
        getContentPane().add(pa);
        pa.setBounds(150, 190, 110, 23);

        pi.setBackground(new java.awt.Color(255, 204, 51));
        buttonGroup1.add(pi);
        pi.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        pi.setForeground(new java.awt.Color(255, 255, 255));
        pi.setText("Perempuan");
        getContentPane().add(pi);
        pi.setBounds(280, 190, 120, 23);

        jButton1.setText("Hitung");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 230, 400, 30);

        jButton2.setText("Coba Lagi");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 260, 200, 30);

        jButton3.setText("Keluar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 260, 210, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Berat badan ideal anda :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 330, 200, 14);

        bbideal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bbideal.setBorder(null);
        getContentPane().add(bbideal);
        bbideal.setBounds(220, 320, 50, 30);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 370, 190, 30);

        hasil1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasil1.setBorder(null);
        getContentPane().add(hasil1);
        hasil1.setBounds(20, 410, 440, 30);

        hasil2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hasil2.setBorder(null);
        getContentPane().add(hasil2);
        hasil2.setBounds(20, 450, 440, 30);

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("cm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 120, 34, 15);

        jLabel10.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 330, 34, 14);

        jLabel11.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("kg");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 160, 34, 15);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 260, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 510);

        setBounds(0, 0, 494, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
            if (nama.getText().equals("")|| tinggi.getText().equals("")|| bb.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data inputan harus diisi");
            }else if(pa.isSelected() || pi.isSelected()){
                try{
                    Proses();
                }catch (Exception e){
                      JOptionPane.showMessageDialog(null, "Data inputan salah");
                }
            }else{
                  JOptionPane.showMessageDialog(null, "Jenis kelamin belum diisi");
            }








        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nama.setText("");
       tinggi.setText("");
       bb.setText("");
       bbideal.setText("");
       hasil1.setText("");
       hasil2.setText("");
       buttonGroup1.clearSelection();
        pa.setSelected(false);
        pi.setSelected(false);
      




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.JTextField bbideal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pa;
    private javax.swing.JRadioButton pi;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tinggi.getText());
        bt = Double.valueOf(bb.getText());
        
        
        if(pa.isSelected()){
            h1 = (ti - 100) * 1;
            
        }else if (pi.isSelected()){
            h1 = (ti - 104) * 1;
            
        }
        temp = Double.toString(h1.intValue());
        
        if(h1 < bt){
            bbideal.setText(temp);
            hasil1.setText("Maaf " + nama.getText() + " , sepertinya anda Overweight :( ");
            hasil2.setText("Banyaklah berolahraga dan hindari makanan kolestrol");
            
        }else if (h1 > bt){
             bbideal.setText(temp);
            hasil1.setText("Maaf " + nama.getText() + " , sepertinya anda Underweight :( ");
            hasil2.setText("Banyaklah mengkonsumsi makanan berkarbohidrat");
        }else{
                bbideal.setText(temp);
            hasil1.setText("Hallo " + nama.getText() + " , berat badan anda sudah ideal :) ");
            hasil2.setText("pertahankanlah pola makan dan olahraga anda");
        }
    }
}
